### ISSUE TITLE
Diode tester script stop issue

### ISSUE THREAD

**Issue by prasimix** [eez-open/modular-psu-firmware#130]
Selecting DLOG Stop while `Diode Tester` script is running will be ignored or could cause restart.

**Comment by prasimix** [comment]
Interrupting the script no longer causes a restart. The question remains whether we want to have a message like this in case of premature termination, or something that is more “graceful”, like "Script terminated"

![diode tester stop](https://user-images.githubusercontent.com/15106476/106315144-1e0b1e80-626b-11eb-8122-ce6e860b0bbb.jpg)

**Comment by mvladic** [comment]
> Interrupting the script ...

Actually, you didn't interrupt the script explicitly - it was side effect of stopping DLOG trace after which `DLOG:TRACE:DATA` failed and this failure wasn't handled inside the script hence "`Uncaught script exception!`"

> The question remains whether we want to have a message like this in case of premature termination, or something that is more “graceful”, like "Script terminated"

I think not, because "`Uncaught script exception!`" is exactly what happened here.

In this particular case we could catch `DLOG:TRACE:DATA` error and reported something like "DLOG stopped, breakdown voltage not found".

**Comment by prasimix** [comment]
> In this particular case we could catch `DLOG:TRACE:DATA` error and reported something like "DLOG stopped, breakdown voltage not found".

OK

**Comment by prasimix** [comment]
Fixed, affected scripts: CapReform (upgraded to 1.5), Curve Tracer (upgraded to 1.4) and Diode Tester (upgraded to 1.3).
