### ISSUE TITLE
OVP changes in RProg mode

### ISSUE THREAD

**Issue by prasimix** [eez-open/modular-psu-firmware#150]
- [x] If OVP HW is active when entering RProg mode, it should be changed to OVP SW because HW will immediately trip due to the principle it works on. When exiting RProg mode, it can return to OVP HW. 
- [x] Reduce OVP trip level from 40.5 to 40.05 and prohibit setting more than 40.05 V.

**Comment by prasimix** [comment]
Fixed

**Comment by fietser28** [comment]
If OVP is OFF (OVP active = OFF) and you enable RProg, OVP is turned ON (software). 
(If I turn RProg OFF then OVP stays ON)
Is this intentional?

When Rprog is tuned on it should:
- change OVP type from HW to SW only if OVP is active HW
- change trip level to 40.05 only if OVP is ON (and being changed to SW). 

Tested on 1.6-RC by going thru menu's. I assume the OVP menu display the settings correctly.

**Comment by prasimix** [comment]
Idea here is to force SW OVP as protection against too high RProg voltage that could lead to module damage if applied for prolonged period of time. Question is if we want to set OVP in previous state or not when RProg is turned off.
