### ISSUE TITLE
Encoder doesn't work correctly with some MCU modules

### ISSUE THREAD

**Issue by prasimix** [eez-open/modular-psu-firmware#269]
If I turn the encoder constantly in one direction, see video (MIO fw v0.11, master fw v1.7.2 beta)

https://user-images.githubusercontent.com/15106476/137517936-da5fb3cf-0908-427c-9961-da69dea88669.mp4

:

**Comment by fietser28** [comment]
This is not specific to AOUT on MIO168. With firmware 1.7.1: If you turn the encoder fast on DCP405 voltage or current settings the value changes intermittently often in the wrong direction. Turning slowly works. Probably a interupt/timing/debounce issue.

**Comment by fietser28** [comment]
https://user-images.githubusercontent.com/8796121/137711214-af7d51c8-d333-4aa1-b937-b7eb43381f86.mov


exaggerated the fast turns a bit for real live, but that makes it more reproducible on a short video. Notice the first fast turn: turning to the right decreased the voltage instead of increasing it...

My experience:
- turning very slow (<1 indents /second) works
- turning slow (<2 indents/sec) only skips a step sometimes, not very often.
- if you go faster it first starts skipping more steps
- going even faster it will occasionally also go in the wrong direction.

The last one is the problem. Maybe limit the speed?

**Comment by prasimix** [comment]
> [0.profile.txt](https://github.com/eez-open/modular-psu-firmware/files/7364014/0.profile.txt)
> 
> I assumed 0 is the active profile.

That can be easily check with `MEM:STAT:REC:SEL?` or on the _User profiles_ page.
